function createfigure(x1, y1)
%CREATEFIGURE(X1,Y1)
%  X1:  vector of x data
%  Y1:  vector of y data
 
%  Auto-generated by MATLAB on 14-Mar-2006 01:17:17
 
%% Create figure
figure1 = figure(...
  'FileName','C:\Documents and Settings\bosisler\My Documents\ders\CMPE360\HW2\untitled.fig',...
  'PaperPosition',[0.6345 6.345 20.3 15.23],...
  'PaperSize',[20.98 29.68]);
 
%% Create axes
axes1 = axes('Parent',figure1);
title(axes1,'Function2');
grid(axes1,'on');
hold(axes1,'all');
 
%% Create plot
plot1 = plot(x1,x1,'Color',[0 0 1]);
 
%% Create plot
plot2 = plot(x1,y1,'Color',[1 0 0]);
 
