(define PEOPLE
'((Hale female ahmet) 
  (Zeynep female Hale Hakan Fatma) 
  (Berna female Ayse) 
  (Mehmet male Asli Ilker) 
  (Hakan male Ayse) 
  (Fatma female Murat) 
  (Hasan male Berna Zehra) 
  (Erdinc male Mehmet Ali Nurgul) 
  (Pinar female Mehmet Ali Nurgul) 
  (Ali male Cenk)
  (Nurgul female Polat)
  (Ahmet male)
  (Ayse female)
  (Asli female)
  (Murat male)
  (Zehra female)
  (Cenk male)
  (Polat male)
  (Ilker male)))