(define PEOPLE
	'((Aysun female Kemal Nesrin Burak)
	(Mahmut male Kemal Nesrin Burak)
	(Kemal male Osman Namik Zeynel)
	(Ayse female Osman Nilgun)
	(Nesrin female Zennur Binnur)
	(Burak male Sibel Riza)
	(Nilay female Sibel Riza)
	(Osman male Aysegul Fatma)
	(Namik male Hayrullah)
	(Ufuk female Hayrullah)
	(Nilgun female)
	(Zennur female)
	(Binnur female)
	(Sibel female)
	(Riza male)
	(Aysegul female)
	(Fatma female)
	(Hayrullah male)
        (Zeynel male)))
	