parent(hale,ahmet). 
parent(zeynep,hale). 
parent(berna,ayse). 
parent(mehmet,asli). 
parent(hakan,ayse). 
parent(zeynep,hakan).
parent(zeynep,fatma).
parent(fatma,murat).
parent(hasan,berna).
parent(hasan,zehra).
parent(erdinc,mehmet).
parent(erdinc,ali).
parent(pinar,mehmet).
parent(pinar,ali).
parent(ali,cenk).
parent(erdinc,nurgul).
parent(nurgul,polat).
parent(pinar,nurgul).
parent(mehmet,ilker).

female(hale).
female(zeynep).
female(berna).
female(ayse).
female(asli).
female(fatma).
female(zehra).
female(pinar).
female(nurgul).

male(ali).
male(ahmet).
male(mehmet).
male(hakan).
male(murat).
male(hasan).
male(erdinc).
male(cenk).
male(polat).
male(ilker).