parent(çisilsu,doða). 
parent(gizem,çisilsu). 
parent(bengi,nesli). 
parent(abdurrahman,derin). 
parent(sertan,nesli). 
parent(gizem,sertan).
parent(gizem,kadriye).
parent(kadriye,kerem).
parent(abuzer,bengi).
parent(abuzer,tergül).
parent(ismail,abdurrahman).
parent(ismail,alican).
parent(belgin,abdurrahman).
parent(belgin,alican).
parent(alican,rýza).
parent(ismail,gülþah).
parent(gülþah,salih).
parent(belgin,gülþah).
parent(abdurrahman,bahadýr).

female(çisilsu).
female(gizem).
female(bengi).
female(nesli).
female(derin).
female(kadriye).
female(tergül).
female(belgin).
female(gülþah).

male(alican).
male(doða).
male(abdurrahman).
male(sertan).
male(kerem).
male(abuzer).
male(ismail).
male(rýza).
male(salih).
male(bahadýr).